---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: priceserver
  namespace: cloudpilot
  labels:
    app.kubernetes.io/component: priceserver
    app.kubernetes.io/name: cloudpilot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: priceserver
  template:
    metadata:
      labels:
        app:  priceserver
        app.kubernetes.io/component:  priceserver
        app.kubernetes.io/name: cloudpilot
    spec:
      containers:
        - name: priceserver
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: ${PRICESERVER_IMAGE_REF}
          args:
            - --v=4
          env:
            - name: AWS_GLOBAL_ACCESS_KEY
              value: ${AWS_GLOBAL_ACCESS_KEY}
            - name: AWS_GLOBAL_SECRET_KEY
              value: ${AWS_GLOBAL_SECRET_KEY}
            - name: AWS_CN_ACCESS_KEY
              value: ${AWS_CN_ACCESS_KEY}
            - name: AWS_CN_SECRET_KEY
              value: ${AWS_CN_SECRET_KEY}
            - name: ALIBABACLOUD_AKSK_POOL
              value: ${ALIBABACLOUD_AKSK_POOL}
          ports:
            - name: server
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 250Mi
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: priceserver
  namespace: cloudpilot
  labels:
    app: priceserver
    app.kubernetes.io/component: priceserver
    app.kubernetes.io/name: cloudpilot
spec:
  selector:
    app: priceserver
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpilot-price-ingress
  namespace: cloudpilot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ${CLOUDPILOT_PRICE_HOST}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: priceserver
            port:
              number: 80
